# Docker Compose file Reference (https://docs.docker.com/compose/compose-file/)

version: '3.7'

# Define services
services:
  # App backend service
  server:
    # Configuration for building the docker image for the backend service
    build:
      context: server # Use an image built from the specified dockerfile in the `server` directory.
      dockerfile: Dockerfile
    ports:
      - "8080:8080" # Map the exposed port 8080 on the container to port 8080 on the host machine
    restart: always
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - frontend

  # Frontend Service 
  web-ui:
    build:
      context: web-ui # Use an image built from the specified dockerfile in the `web-ui` directory.
      dockerfile: Dockerfile
      args:
        REACT_APP_API_BASE_URL: http://localhost:8080/api
    ports:
      - "3000:80" # Map the exposed port 80 on the container to port 3000 on the host machine
    restart: always
    depends_on:
      - server
    networks:
      - frontend  

# Networks to be created to facilitate communication between containers
networks:
  frontend:
